version: '3.3'

services:
    php5:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: php5
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}nginx_base/1.15.3:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}nginx_base/1.15.3:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: php5
        container_name: php5
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
#            PWD_PROTECTED: 'true'
#            WEB_USER_ID: $CFG_USER
#            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
        hostname: php5
        image: ${DOCKER_REGISTRY:-}${OS:-}php/5.6.37-r0:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
           - 80:80
           - 9001:9001
# only use when building a 'service container' # only use when building a 'service container'
#        restart: unless-stopped
        secrets:
            - supervisord.pwd
#            - web_user.pwd

secrets:
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
