version: '3.5'

services:
    php5:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: php5
                CONTAINER_VERSION: 1.0.8
                DEBUG_TRACE: 0
                FROM_BASE: supervisord:20180329
            cache_from:
                - alpine:3.6
                - base_container:20180329
                - supervisord:20180329
            context: .
            dockerfile: Dockerfile
        container_name: php5
        hostname: php5
        image: php5:20180329
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
# only use when building a 'service container'
#        restart: unless-stopped
