version: '3.5'

services:
    php5:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: php5
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: supervisord:latest
            cache_from:
                - alpine:3.6
                - base_container:latest
                - supervisord:latest
            context: .
            dockerfile: Dockerfile
        container_name: php5
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: php5
        image: php5:latest
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
# only use when building a 'service container'
#        restart: unless-stopped
